'Zero':
  - [0, 0, 0, 0, 0]
'One':
  - [0, 1, 0, 0, 0]
'Two':
  - [0, 1, 1, 0, 0]
'Three':
  - [0, 0, 1, 1, 1]
  - [0, 1, 1, 1, 0]
'Four':
  - [0, 1, 1, 1, 1]
'Five':
  - [1, 1, 1, 1, 1]
'Six':
  - [1, 0, 0, 0, 0]
'Seven':
  - [1, 1, 0, 0, 0]
'Eight':
  - [1, 1, 1, 0, 0]
'Nine':
  - [1, 1, 1, 1, 0]
